name: Lint checking

on: [push]

jobs: 
    lint-check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Run eslint check
              run: npm run lint
    